apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: { { .Values.services.backend.port } }
      targetPort: { { .Values.services.backend.port } }
  type: { { .Values.services.backend.type } }
