apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: { { .Values.services.frontend.port } }
      targetPort: { { .Values.services.frontend.port } }
      nodePort: { { .Values.services.frontend.nodePort } }
  type: { { .Values.services.frontend.type } }
