apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
    - name: http
      port: { { .Values.services.redis.port } }
      targetPort: { { .Values.services.redis.port } }
  type: { { .Values.services.redis.type } }
