backend:
  image: shreybatra/sample-backend
  port: 8000
  replicas: 1
  env:
    REDIS_URI: redis://redis-svc:6379

frontend:
  image: shreybatra/sample-frontend
  port: 5175
  env:
    BACKEND_URL: http://backend-svc:8000

redis:
  image: redis
  port: 6379

services:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: NodePort
    port: 5175
    nodePort: 31000
  redis:
    type: ClusterIP
    port: 6379
